---
title: Jekyll Test
timezone: UTC
collections:
  archive:
    title: Archive
    output: true
    permalink: "/archive/:title"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    layout:
    date:
    title:
    image:
name: Jarrett Fuller
description: Designer, Writer, Podcaster
avatar:
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github:
  instagram:
  linkedin:
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:
google_analytics: UA-91441149-1
url:
baseurl: ''
highlighter: rouge
permalink: "/:title/"
version: v1.1.0
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
